### ISSUE TITLE
Lit review: how  DER SPIEGEL  uses Svelte - D3 for their graphics desk

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/interactivity#10]
- [x] watch https://www.youtube.com/watch?v=JDEtUjjdVag&list=LL&index=2&t=905s&ab_channel=FrontendRheinMain
- [x] write zettle summarizing
     - [x] why d3 + svelte
     - [x] reproduce example if avaiable
     - [x] search if hey have github and any open soruced code we could potential use.

**Comment by ran-codes** [comment]
@anujtanwar98 at ~ 42 minut they talk about how to do transitions needed for #11

**Comment by anujtanwar98** [comment]
[link to notes](https://github.com/Drexel-UHC/interactivity/blob/main/obsidian/d3%20notes/why%20d3%20%2B%20svelte/Svelte%20and%20D3.md)
