### ISSUE TITLE
d3 map bubble

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/interactivity#13]
- [x] map 1: no bubble just the US state boundaries [live map a](https://interactivity-v0.netlify.app/chartmap)
- [x] map 2:  US state boundaries + a single dot at each county [live map b](https://interactivity-v0.netlify.app/chartmapb)
- [x] map 3: add data to each dot via a radius scale [live map c](https://interactivity-v0.netlify.app/chartmapc)
- [x] map 4: add some transition [live map d](https://interactivity-v0.netlify.app/chartmapd)
- [x] map 5: create chloropleth (https://observablehq.com/@d3/choropleth)
   - [x] adding fill. mapping 'data' to the fill color
   - [x] adding a scale.  [live link for map 5](https://interactivity-v0.netlify.app/chartmape)
- [x] map 6: add reactivity (https://observablehq.com/d/455a17269cad9755)
   - [x] add a drop down that lets us select which data to plot 
   - [x] link this to the d3 map... and change the data that is mapped (with transition)  [live link for map 6](https://interactivity-v0.netlify.app/chartmapf)
- [x] map 7: extend map 6 but 
    - [x] add a scale that 
    - [x] updates scale pallete dependent dataset. data 1 (blueish) data 2 ([orangish](https://colorbrewer2.org/#type=sequential&scheme=Oranges&n=3)). 
    - [x] move scale so its not overlapping with map [live link](https://interactivity-v0.netlify.app/chartmapg)
- [x] map 8: state specific zoom/transition
   - [x]  in the drop down: add the following options (1. US 2. PA)
   - [x] if dropdown > US:  just as is https://interactivity-v0.netlify.app/chartmape
   - [x] if dropdown > CA: zoom into CA, remove/hide other states, scale need to update just with the CA range of data. play around with transition, try to make it smooth.  [map 9](https://interactivity-v0.netlify.app/chartmapj)

**Comment by ran-codes** [comment]
action items for map 8
- event observer on state that updates reactive value 
- this state reactive value should be text somehwere on top so we can see what that reative value is (e.g. NY, All State)
- how to zoom into a particular state
- how to make all other states blank 
- then update the scale accordingly so its based on state level ranges
- create zoom out logici to restore US level

**Comment by anujtanwar98** [comment]
[work in progress for map 8](https://interactivity-v0.netlify.app/chartmapi)

**Comment by ran-codes** [comment]
Anuj can you keep map 8 as is. and just add the remaining features to map 9? (i want to track changes I think map 8 as shown above is already huge milestone!) 

Thanks!!

**Comment by anujtanwar98** [comment]
[live link of map 9](https://interactivity-v0.netlify.app/chartmapj)

**Comment by anujtanwar98** [comment]
new map more interactive and can click to any state https://interactivity-v0.netlify.app/chartmapk
