### ISSUE TITLE
Set up obsidian

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/interactivity#2]
- [ ] install obsidian
- [ ]  clone `uxid-coop` repo
- [ ] set up obsidiant in `root/obsidian/` folder
- [ ] push
- [ ] draft notes on D3 
  - [ ] start with single markdown
  - [ ] expand as needed
  - [ ] Use chat GPT to get high level exaplianin of D3 + basic D3 concept

**Comment by ran-codes** [comment]
@anujtanwar98 i updated the instructions a bit here. please set up the obsidian project in this repository at the folder above. Thanks!!

**Comment by anujtanwar98** [comment]
@ran-codes I did setup of obsidian and also commit about d3. One more thing i setup which is obsidian git to commit my code to a private repo
