### ISSUE TITLE
JS array methods blog post (zettle or observable)

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/interactivity#5]
- [x]  do research what are common array methods used in JS
- [x] for each method  Explain and show exmaples of the following array methods

For example:
- filter
- slice
- pop
- mutate?
- map!!
- reduce

**Comment by anujtanwar98** [comment]
[My notes for JS Arrays Methods](https://github.com/Drexel-UHC/interactivity/blob/main/obsidian/d3%20notes/JS-array-methods/About%20JS%20Array%20methods.md)
