### ISSUE TITLE
set up UI framework

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/interactivity#9]
# Setup  @ran-codes 
- [x] try to reproduce our app with skeleton.dev 
- [x] card  component
- [x] abstract Button to own component
- [x] Add drawer 
- [x] add Button as a list item
- [x] Abstract some D3 componts to drawer

# Content population @anujtanwar98 
- [x] npm i
- [x] npm run prepare
- [x]  Anuj to fill in the rest of line chart components  ( LineC.svelte, LineD.svelte ... ETC)
- [x]  update components>Line>TabsetLine.svelte
- [x] repeat process for TabsetBox
- [x] Add TabsetBox to D3Drawer
- [x] repeat process for TabsetScatter 
- [x] Add TabsetScatter to D3Drawer
- [x] deploy to netlify (interactivity_v0 or uhc_....)

**Comment by anujtanwar98** [comment]
when i try to use card component it make two card and othe components sometimes doesn't work.
